In [1]:
import numpy as np

In [3]:
P = np.array([[1, 7], [2, 1], [3, 2]])
Q = np.array([[1, 1], [1, -1], [1, 0]])

print(P)
print(Q)

[[1 7]
 [2 1]
 [3 2]]
[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [5]:
C = np.add(P, Q) # subtract
print(C)

[[2 8]
 [3 0]
 [4 2]]


In [6]:
print(P+Q) # -

[[2 8]
 [3 0]
 [4 2]]


In [7]:
R = np.array([[1, 3, 1], [1, 0, 1]])

In [14]:
C2 = np.dot(P, R)

In [10]:
print(P*Q)

[[ 1  7]
 [ 2 -1]
 [ 3  0]]


In [16]:
print(np.linalg.det(C2)) # determinant

# C2 is singular matrix.

0.0


In [17]:
M = np.array([[1, -1], [2, 3]])
print(np.linalg.inv(M))

[[ 0.6  0.2]
 [-0.4  0.2]]
