In [1]:
import numpy as np

In [2]:
# vector is one dimensional
v = np.array([1, -1, 2])
w = np.array([2, 5, 2])

print(v+w)

[3 4 4]


In [3]:
print(v-w)

[-1 -6  0]


In [4]:
# Scalar Multiplication
print(3 * v)

[ 3 -3  6]


In [5]:
# length - linalg = linear algebra
print(np.linalg.norm(v))

2.449489742783178


In [6]:
print(np.dot(v, w))

1
