In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a[0]

1

In [3]:
a = np.array([[1,2], [3,4], [5,6]]) # 2 D
a.ndim

2

In [4]:
a.itemsize # Int Size

4

In [5]:
a.dtype

dtype('int32')

In [6]:
a.shape

(3, 2)

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.arange(1,5)

array([1, 2, 3, 4])

In [10]:
np.linspace(1,5,10) # 10 number between 1 and 5.. Difference is equal.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
a = np.array([[1,2], [3,4], [5,6]])

In [12]:
a.shape

(3, 2)

In [13]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a.shape

(3, 2)

In [15]:
a.ravel() # Flat Array

array([1, 2, 3, 4, 5, 6])

In [16]:
a.min()

1

In [17]:
a.sum()

21

In [18]:
a.sum(axis=0)

array([ 9, 12])

In [19]:
a.sum(axis=1)

array([ 3,  7, 11])

In [20]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [21]:
np.std(a)

1.707825127659933

In [22]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [23]:
a + b

array([[ 6,  8],
       [10, 12]])

In [24]:
a * b

array([[ 5, 12],
       [21, 32]])

In [25]:
a.dot(b)

array([[19, 22],
       [43, 50]])