In [1]:
import numpy as np

In [3]:
l = [6, 7, 8]
l[0:2] # Start(Included):End(Excluded)

[6, 7]

In [4]:
l[-1] # End

8

In [6]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [7]:
a[-1]

8

In [8]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [9]:
a[1][2] # 1 is row and 2 is column

3

In [10]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [11]:
a[0:2, 2] # 0 and 1 row, 2nd column

array([8, 3])

In [12]:
a[-1] # last row

array([9, 3, 2])

In [13]:
a[-1, 0:2] # Last row, 0 and 1st column

array([9, 3])

In [14]:
a[:, 1:3] # all rows and 1, 2 column

array([[7, 8],
       [2, 3],
       [3, 2]])

In [15]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [16]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [17]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [22]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
np.hsplit(a,3) # Split array into 3 arrays horizonantly.

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [24]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b = a > 4 # Create boolean matrix by comparing all elements of a with 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
a[b] # Retrun only True values array from a.

array([ 5,  6,  7,  8,  9, 10, 11])

In [28]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])