In [1]:
import torch
import numpy as np

# Tensor Initialization

In [2]:
# From Data Directly

data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# From NumPy Array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
# From Another Tensor
x_ones = torch.ones_like(x_data) # Retain the property of x_data
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) # Override data type.
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8552, 0.7378],
        [0.9958, 0.4832]])


In [5]:
# With random or constant values
shape = (2,3,) # a tuple of tensor dimension.
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(rand_tensor)
print(one_tensor)
print(zero_tensor)

tensor([[0.2589, 0.0687, 0.6910],
        [0.7393, 0.5945, 0.5408]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor Attributes

In [6]:
# It describe shape, datatype and device on which it is stored.

tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


# Tensor Operation

In [7]:
# Move tensor to GPU if available

if torch.cuda.is_available():
    print("GPU available")
    tensor.to('cuda')

print(tensor.device)

cpu


In [8]:
# Indexing and Slicing
tensor = torch.ones(4,4)
tensor[:, 1] = 0

print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# Joining Tensors - torch.cat and torch.stack

t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [10]:
# Multiply tensors - Compute element wise product
print(tensor.mul(tensor))
print(tensor * tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# Matrix Multiplication
print(tensor.matmul(tensor.T))
print(tensor @ tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [12]:
# inplace operation - Will change the object itself. "_" suffix.
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

# Bridge with Numpy

In [14]:
# tensor and numpy on cpu can share the memory. change in one will change other.
t = torch.ones(5)
n = t.numpy()
t.add_(1)
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n,1,out=n)

t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)